
### 获取配置信息

GET {{host}}/api/v1/config?pId=(string)&dId=(string)
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}


### 心跳

POST {{host}}/api/v1/heartbeat
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

dId=${1.data}&pId=${1.data.url}

